export class ContractsVM {
    contractId: number;
    contractNo: string | null;
    date: string | null;
    hijriDate: string | null;
    customerId: number | null;
    projectId: number | null;
    cityId: number | null;
    instrumentNo: string | null;
    instrumentDate: string | null;
    type: number |null;
    value: number |null;
    valueText: string | null;
    district: string | null;
    taxType: number|null;
    taxesValue: number | null;
    branchId: number|null;
    attachmentUrl: string | null;
    customerName: string | null;
    customerName_W: string | null;
    customerMobile: string | null;
    projectName: string | null;
    projectNo: string | null;
    customerTypeName: string | null;
    projectTypeName: string | null;
    totalRemainingPayment: number | null;
    totalPaidPayment: number | null;
    paymentHijriDate: string | null;
    advancePayValue: number |null;
    monthlyPayValue: number|null;
    paymentsCount: number|null;
    lastPayValue: number|null;
    gregorianHijriPay: number|null;
    payType: number|null;
    totalValue: number | null;
    totalValuetxt: string | null;
    orgId: number | null;
    orgEmpId: number | null;
    orgEmpJobId: number | null;
    serviceId: number | null;
    isChecked: boolean;
    isSearch: boolean;
    dateFrom: string | null;
    dateTo: string | null;
    updateUser: number | null;
    serviceName: string | null;
    attachmentUrlExtra: string | null;
    engineering_License: string | null;
    engineering_LicenseDate: string | null;
    appr_LetterDate_Des: string | null;
    engServ_OfferDate_Des: string | null;
    maxPay_Des: string | null;
    contractDurCommit_Des: string | null;
    contPeriod_Des: string | null;
    teamWork_Num1_Des: string | null;
    teamWork_Note1_Des: string | null;
    teamWork_Num2_Des: string | null;
    teamWork_Note2_Des: string | null;
    teamWork_Num3_Des: string | null;
    teamWork_Note3_Des: string | null;
    teamWork_Num4_Des: string | null;
    teamWork_Note4_Des: string | null;
    teamWork_Num5_Des: string | null;
    teamWork_Note5_Des: string | null;
    teamWork_Num6_Des: string | null;
    teamWork_Note6_Des: string | null;
    teamWork_Num7_Des: string | null;
    teamWork_Note7_Des: string | null;
    teamWork_Num8_Des: string | null;
    teamWork_Note8_Des: string | null;
    teamWork_Num9_Des: string | null;
    teamWork_Note9_Des: string | null;
    teamWork_Num10_Des: string | null;
    teamWork_Note10_Des: string | null;
    cons_TotalFees_Des: string | null;
    contractorName_Des: string | null;
    contDate_Des: string | null;
    projBriefDesc_Des: string | null;
    totalServiceCount: number | null;
    projectDescription: string | null;
    managerId: number | null;
    oper_expeValue: number | null;
    firstProjectDate: string | null;
    firstProjectExpireDate: string | null;
    stopProjectType: number | null;
}