import { Auditable } from "../DomainObjects/auditable";
import { EmpContractDetailVM } from "./empContractDetailVM";

export class EmpContractVM extends Auditable {
    contractId: number;
    contractCode: string | null;
    orgId: number;
    companyRepresentativeId: number;
    perSe: string | null;
    empId: number;
    contTypeId: number | null;
    contDuration: number | null;
    startDatetxt: string | null;
    startWorkDate: string | null;
    endWorkDate: string | null;
    endDatetxt: string | null;
    probationDuration: number | null;
    workingdaysperweek: number;
    dailyworkinghours: number;
    workinghoursperweek: number;
    durationofannualleave: number;
    freelanceAmount: number | null;
    paycase: number;
    probationTypeId: number;
    restrictedmode: number;
    notTodivulgeSecrets: number;
    restrictionDuration: number;
    identifyplaces: string | null;
    withregardtowork: string | null;
    notTodivulgeSecretsDuration: number | null;
    secretsIdentifyplaces: string | null;
    secretsWithregardtowork: string | null;
    contractTerminationNotice: number | null;
    compensation: number;
    compensationBothParty: number | null;
    firstpartycompensation: number | null;
    secondpartycompensation: number | null;
    year: number;
    date: string | null;
    hijriDate: string | null;
    nationalityId: number | null;
    branchId: number;
    employeeName: string | null;
    branchName: string | null;
    isSearch: boolean;
    natName: string | null;
    nationalityName: string | null;
    addUsers: string | null;
    updateUsers: string | null;
    dailyEmpCost: number | null;
    employeeno: string | null;
    empContractDetails: EmpContractDetailVM[];
}
