export class OrganizationsVM {
    organizationId: number;
    nameAr: string | null;
    nameEn: string | null;
    mobile: string | null;
    email: string | null;
    logoUrl: string | null;
    serverName: string | null;
    address: string | null;
    webSite: string | null;
    fax: string | null;
    cityId: number | null;
    reportType: number | null;
    taxCode: string | null;
    notificationsMail: string | null;
    vAT: number;
    vATSetting: number;
    postalCode: string | null;
    password: string | null;
    senderName: string | null;
    host: string | null;
    port: string | null;
    sSL: boolean;
    accountBank: string | null;
    isFooter: string | null;
    editUserName: string | null;
    editUserDate: string | null;
    representorEmpId: number | null;
    postalCodeFinal: string | null;
    externalPhone: string | null;
    country: string | null;
    neighborhood: string | null;
    streetName: string | null;
    buildingNumber: string | null;
    accountBank2: string | null;
    engineering_License: string | null;
    engineering_LicenseDate: string | null;
    comDomainLink: string | null;
    comDomainAddress: string | null;
    cityName: string | null;
    orgName: string | null;
    bankId: number | null;
    bankId2: number | null;
    bankIdImgURL: string | null;
    bankId2ImgURL: string | null;
    cSR: string | null;
    privateKey: string | null;
    publicKey: string | null;
    secreteKey: string | null;
    apiBaseUri: string | null;
    lastvesionAndroid: string | null;
    lastversionIOS: string | null;
    messageUpdateAr: string | null;
    messageUpdateEn: string | null;
    supportMessageAr: string | null;
    supportMessageEn: string | null;
}