export class ReportCustomer {
  type: number;
  dateFrom: string | null;
  dateTo: string | null;
  voucherNo: string |number | null;
  isSearch: boolean |string | null;
  isPost: number |string | null;
  projectId: number |string | null;
  isChecked: boolean |string | null;
  isCheckedYear: boolean |string | null;
  isCheckedBranch: boolean |string | null;
  isDeleted: boolean |string | null;
  customerId: number |string | null;
  status: number |string | null;
  supplierId: number |string | null;
  accountId: number |string | null;
  qRCode: string | null;
  invoiceNote: string | null;
  pageInsert: number |string | null;
  zeroCheck: number |string | null;
  lvl: number |string | null;
  ccid: number |string | null;
  filtertypeid: number |string | null;
  filteringTypeAll: number |string | null;
  filteringType: number |string | null;
  FilteringTypeStr: number |string | null;
  FilteringTypeAllStr: number |string | null;
  CostCenter: number |string | null;
  FromJournal: number |string | null;
  ToJournal: number |string | null;
  search_accountId: number |string | null;
  projectNo:any;
  Sortedlist:any;
  ManagerName:any;
  CostCenterName:any;
  DateId:any;
  SortedlistJournalNo:any;
  SortedlistAccountCode:any;
  rasedBefore:any;
  periodFillterType:any;
  periodCounter:any;
  typeF:any;
  employeeId:any;
}
