import { ProjectPhasesTasksVM } from "./projectPhasesTasksVM";
import { ProjectVM } from "./projectVM";

export class UsersVM {
    userId: number;
    fullName: string | null;
    jobId: number | null;
    departmentId: number | null;
    email: string | null;
    mobile: string | null;
    groupId: number | null;
    branchId: number | null;
    imgUrl: string | null;
    empId: number | null;
    userName: string | null;
    password: string | null;
    status: number | null;
    session: number | null;
    recoverPasswordLink: string | null;
    recoverPasswordDate: string | null;
    expireDate: string | null;
    notes: string | null;
    departmentName: string | null;
    jobName: string | null;
    groupName: string | null;
    branchName: string | null;
    isOnline: boolean | null;
    lastSeenDate: string | null;
    lastLoginDate: string | null;
    iSOnlineNew: boolean | null;
    isAdmin: boolean | null;
    activeTime: string | null;
    branchManager: string | null;
    stampUrl: string | null;
    timeId: number | null;
    accStatusConfirm: string | null;
    supEngineerName: string | null;
    supEngineerNationalId: string | null;
    supEngineerCert: string | null;
    fullNameAr: string | null;
    fullNameEn: string | null;
    deviceId: string | null;
    addUsers: string | null;
    tokenkey: string | null;
    userPrivilliges: number[];
    latetask_VM: ProjectPhasesTasksVM[] | null;
    inprogress_VM: ProjectPhasesTasksVM[] | null;
    stoppedTasks_VM: ProjectPhasesTasksVM[] | null;
    notstarted_VM: ProjectPhasesTasksVM[] | null;
    completed_VM: ProjectPhasesTasksVM[] | null;
    retrived_VM: ProjectPhasesTasksVM[] | null;
    completePercentage_VM: ProjectPhasesTasksVM[] | null;
    latePercentage_VM: ProjectPhasesTasksVM[] | null;
    almostLate_VM: ProjectPhasesTasksVM[] | null;
    projectLate_VM: ProjectVM[] | null;
    projectInProgress_VM: ProjectVM[] | null;
    projectStoped_VM: ProjectVM[] | null;
    projectWithout_VM: ProjectVM[] | null;
    projectWithout_VM2: ProjectVM[] | null;
    allProject_VM: ProjectVM[] | null;
    projectWork_VM: ProjectVM[] | null;
    projectAlmostfinish_VM: ProjectVM[] | null;
    allPhases_VM: ProjectPhasesTasksVM[] | null;
    allFinishPhases_VM: ProjectPhasesTasksVM[] | null;
    allLatePhases_VM: ProjectPhasesTasksVM[] | null;
    latetask: string | null;
    inprogress: string | null;
    notstarted: string | null;
    completed: string | null;
    retrived: string | null;
    completePercentage: number;
    latePercentage: number;
    almostLate: string | null;
    projectLate: string | null;
    projectInProgress: string | null;
    projectStoped: string | null;
    projectWithout: string | null;
    projectAlmostfinish: string | null;
    isActivated: boolean | null;
    encryptedCode: string | null;
    appearWelcome: number | null;
    qrCodeUrl: string | null;
    deviceType: number | null;
    deviceTokenId: string | null;
    appearInInvoicePrint: number | null;
}
