import { Auditable } from "./auditable";
import { CustomerPayments } from "./customerPayments";
import { Customer } from "./customer";
import { Project } from "./project";
import { Transactions } from "./transactions";
import { ContractDetails } from "./contractDetails";
import { ContractStage } from "./contractStage";
import { Service } from "./services";
import { ContractServices } from "./contractServices";

export class Contracts extends Auditable {
    contractId: number;
    contractNo: string | null;
    date: string | null;
    hijriDate: string | null;
    customerId: number | null;
    projectId: number | null;
    cityId: number | null;
    instrumentNo: string | null;
    instrumentDate: string | null;
    type: number;
    value: number;
    valueText: string | null;
    district: string | null;
    taxType: number;
    taxesValue: number | null;
    branchId: number;
    attachmentUrl: string | null;
    customerPayments: CustomerPayments[] | null;
    customer: Customer | null;
    project: Project | null;
    transactionDetails: Transactions[] | null;
    totalValue: number | null;
    totalValuetxt: string | null;
    orgId: number | null;
    orgEmpId: number | null;
    orgEmpJobId: number | null;
    serviceId: number | null;
    attachmentUrlExtra: string | null;
    engineering_License: string | null;
    engineering_LicenseDate: string | null;
    appr_LetterDate_Des: string | null;
    engServ_OfferDate_Des: string | null;
    maxPay_Des: string | null;
    contractDurCommit_Des: string | null;
    contPeriod_Des: string | null;
    teamWork_Num1_Des: string | null;
    teamWork_Note1_Des: string | null;
    teamWork_Num2_Des: string | null;
    teamWork_Note2_Des: string | null;
    teamWork_Num3_Des: string | null;
    teamWork_Note3_Des: string | null;
    teamWork_Num4_Des: string | null;
    teamWork_Note4_Des: string | null;
    teamWork_Num5_Des: string | null;
    teamWork_Note5_Des: string | null;
    teamWork_Num6_Des: string | null;
    teamWork_Note6_Des: string | null;
    teamWork_Num7_Des: string | null;
    teamWork_Note7_Des: string | null;
    teamWork_Num8_Des: string | null;
    teamWork_Note8_Des: string | null;
    teamWork_Num9_Des: string | null;
    teamWork_Note9_Des: string | null;
    teamWork_Num10_Des: string | null;
    teamWork_Note10_Des: string | null;
    cons_TotalFees_Des: string | null;
    contractorName_Des: string | null;
    contDate_Des: string | null;
    projBriefDesc_Des: string | null;
    oper_expeValue: number | null;
    contractDetails: ContractDetails[] | null;
    contractStage: ContractStage[] | null;
    service: Service | null;
    contractServices: ContractServices[] | null;
}
