import { Auditable } from "./auditable";
import { Branch } from "./branch";
import { Nationality } from "./nationality";
import { Employees } from "./employees";
import { EmpContractDetail } from "./empContractDetails";
import { Users } from "./users";

export class EmpContract extends Auditable {
    contractId: number;
    contractCode: string | null;
    orgId: number;
    companyRepresentativeId: number;
    perSe: string | null;
    empId: number;
    contTypeId: number | null;
    contDuration: number | null;
    startDatetxt: string | null;
    startWorkDate: string | null;
    endWorkDate: string | null;
    endDatetxt: string | null;
    probationDuration: number | null;
    workingdaysperweek: number;
    dailyworkinghours: number;
    workinghoursperweek: number;
    durationofannualleave: number;
    freelanceAmount: number | null;
    paycase: number;
    probationTypeId: number;
    restrictedmode: number;
    notTodivulgeSecrets: number;
    restrictionDuration: number;
    identifyplaces: string | null;
    withregardtowork: string | null;
    notTodivulgeSecretsDuration: number | null;
    secretsIdentifyplaces: string | null;
    secretsWithregardtowork: string | null;
    contractTerminationNotice: number | null;
    compensation: number;
    compensationBothParty: number | null;
    firstpartycompensation: number | null;
    secondpartycompensation: number | null;
    year: number;
    date: string | null;
    hijriDate: string | null;
    branchId: number;
    nationalityId: number | null;
    dailyEmpCost: number | null;
    branchName: Branch | null;
    natName: Nationality | null;
    employees: Employees | null;
    empContractDetails: EmpContractDetail[] | null;
    addUsers: Users | null;
    updateUsers: Users | null;
}
