import { Auditable } from './auditable';
import { Department } from './department';
import { Users } from './users';
import { Branch } from './branch';
import { Job } from './job';
import { AttendaceTime } from './attendaceTime';
import { Banks } from './banks';
import { Accounts } from './accounts';
import { Nationality } from './nationality';
import { NodeLocations } from './nodeLocations';
import { Allowance } from './allowance';
import { Loan } from './loan';
import { Custody } from './custody';
import { DiscountReward } from './discountReward';
import { AttAbsentDay } from './attAbsentDay';
import { Vacation } from './vacations';
import { ExpensesGovernment } from './expensesGovernment';
import { PayrollMarches } from './payrollMarches';

export class Employees extends Auditable {
  employeeId: number;
  employeeNo: string | null;
  employeeNameAr: string | null;
  employeeNameEn: string | null;
  jobId: number | null;
  religionId: number | null;
  departmentId: number | null;
  nationalityId: number | null;
  bankId: number | null;
  gender: number | null;
  email: string | null;
  mobile: string | null;
  address: string | null;
  nationalId: string | null;
  passportNo: string | null;
  photoUrl: string | null;
  nationalIdDate: string | null;
  nationalIdHijriDate: string | null;
  passportNoDate: string | null;
  passportNoHijriDate: string | null;
  salary: number | null;
  discount: number | null;
  bonus: number | null;
  rewards: number | null;
  allowances: number | null;
  loan: number | null;
  beginWorkDate: string | null;
  beginWorkHijriDate: string | null;
  endWorkDate: string | null;
  endWorkHijriDate: string | null;
  bankCardNo: string | null;
  bankDate: string | null;
  bankHijriDate: string | null;
  haveLicence: boolean;
  licenceNo: string | null;
  licenceStartDate: string | null;
  licenceStartHijriDate: string | null;
  licenceEndDate: string | null;
  licenceEndHijriDate: string | null;
  licenceSource: string | null;
  liscenseSourceId: number | null;
  accountId: number | null;
  educationalQualification: string | null;
  birthDate: string | null;
  birthHijriDate: string | null;
  birthPlace: string | null;
  telephone: string | null;
  mailbox: string | null;
  userId: number | null;
  branchId: number | null;
  childrenNo: number | null;
  maritalStatus: number | null;
  active: boolean;
  usrId: number | null;
  nationalIdSource: number | null;
  nationalIdEndDate: string | null;
  nationalIdEndHijriDate: string | null;
  passportSource: string | null;
  passportEndDate: string | null;
  passportEndHijriDate: string | null;
  contractNo: string | null;
  contractStartDate: string | null;
  contractStartHijriDate: string | null;
  contractSource: string | null;
  contractEndDate: string | null;
  contractEndHijriDate: string | null;
  workNo: string | null;
  workStartDate: string | null;
  workStartHijriDate: string | null;
  workSource: string | null;
  medicalNo: string | null;
  medicalSource: string | null;
  medicalStartDate: string | null;
  medicalStartHijriDate: string | null;
  medicalEndDate: string | null;
  medicalEndHijriDate: string | null;
  medNo: string | null;
  medDNo: string | null;
  medSource: string | null;
  medDSource: string | null;
  medDate: string | null;
  medHijriDate: string | null;
  medDDate: string | null;
  medDHijriDate: string | null;
  medEndDate: string | null;
  medEndHijriDate: string | null;
  medDEndDate: string | null;
  medDEndHijriDate: string | null;
  dawamId: number | null;
  timeDurationLate: number | null;
  logoutDuration: number | null;
  afterLogoutTime: number | null;
  deppID: number | null;
  vacationsCount: number | null;
  citySourceId: number | null;
  nationalIdEndCount: number | null;
  passportEndCount: number | null;
  contractEndCount: number | null;
  licenceCarEndCount: number | null;
  medicalEndCount: number | null;
  vacationEndCount: number | null;
  loanCount: number | null;
  locationId: number | null;
  postalCode: string | null;
  department: Department;
  accountIDs: number | null;
  taamen: string | null;
  earlyLogin: number | null;
  accountIDs_Discount: number | null;
  accountIDs_Bouns: number | null;
  accountIDs_Salary: number | null;
  accountIDs_Custody: number | null;
  resonLeave: string | null;
  empServiceDuration: string | null;
  users: Users | null;
  branch: Branch | null;
  job: Job | null;
  attendaceTime: AttendaceTime | null;
  bank: Banks | null;
  account: Accounts | null;
  nationality: Nationality | null;
  nodeLocations: NodeLocations | null;
  directManager: number | null;
  beginWork: string | null;
  allowance: Allowance[] | null;
  loans: Loan[] | null;
  custodies: Custody[] | null;
  discountRewards: DiscountReward[] | null;
  attAbsentDays: AttAbsentDay[] | null;
  vacations: Vacation[] | null;
  expensesGovernment: ExpensesGovernment[] | null;
  payrollMarches: PayrollMarches[] | null;

  otherAllownces: number | null;
}
