import { Auditable } from './auditable';
import { Accounts } from './accounts';
import { Users } from './users';
import { VoucherDetails } from './voucherDetails';
import { Transactions } from './transactions';
import { Customer } from './customer';
import { Acc_Suppliers } from './acc_Suppliers';
import { Project } from './project';
import { Branch } from './branch';
import { AccTransactionTypes } from './accTransactionTypes';

export class Invoices extends Auditable {
  invoiceId: number;
  invoiceNumber: string | null;
  type: number;
  customerId: number | null;
  date: string | null;
  hijriDate: string | null;
  currencyId: number | null;
  exchangeRate: number | null;
  orderId: number | null;
  rad: boolean | null;
  delegateId: number | null;
  notes: string | null;
  storeId: number | null;
  journalNumber: number | null;
  isPurchaseReturn: boolean | null;
  invoiceValue: number | null;
  discountPercentage: number | null;
  discountValue: number | null;
  totalValue: number | null;
  invoiceValueText: string | null;
  paid: number | null;
  paidRequired: number | null;
  totalExpenses: number | null;
  branchId: number | null;
  isPost: boolean | null;
  postDate: string | null;
  postHijriDate: string | null;
  yearId: number | null;
  currentOp: number | null;
  userId: number | null;
  receiverName: string | null;
  invoiceReference: string | null;
  projectId: number | null;
  toAccountId: number | null;
  voucherType: number | null;
  toInvoiceId: number | null;
  isTax: boolean | null;
  taxAmount: number | null;
  payType: number | null;
  numberOfDepit: number | null;
  numberOfCredit: number | null;
  printBankAccount: boolean | null;
  paidValue: number | null;
  supplierInvoiceNo: string | null;
  recevierTxt: string | null;
  clauseId: number | null;
  supplierId: number | null;
  costCenterId: number | null;
  pageInsert: number | null;
  qRCodeNum: string | null;
  invoiceNotes: string | null;
  recycleYearTo: string | null;
  recycleStatus: boolean | null;
  invoiceRetId: string | null;
  dunCalc: boolean | null;
  fileName: string | null;
  fileUrl: string | null;
  voucherAlarmDate: string | null;
  voucherAlarmCheck: boolean | null;
  isSendAlarm: number | null;
  movementId: number | null;
  creditNotiId: number | null;
  depitNotiId: number | null;
  invUUID: string | null;
  voucherAdjustment: boolean | null;
  invoiceHash: string | null;
  singedXML: string | null;
  encodedInvoice: string | null;
  zatcaUUID: string | null;
  qRCode: string | null;
  pIH: string | null;
  singedXMLFileName: string | null;
  supplierInvoiceNotxt: string | null;
  accounts: Accounts | null;
  addUsers: Users | null;
  voucherDetails: VoucherDetails[] | null;
  invoices_Credit: Invoices | null;
  invoices_Depit: Invoices | null;
  transactionDetails: Transactions[] | null;
  customer: Customer | null;
  suppliers: Acc_Suppliers | null;
  project: Project | null;
  branch: Branch | null;
  accTransactionTypes: AccTransactionTypes | null;
  fromAccountId: number | null;
}
