import { Auditable } from "./auditable";
import { CustomerPayments } from "./customerPayments";
import { OffersConditions } from "./offersConditions";
import { OfferService } from "./offerService";
import { Customer } from "./customer";
import { Users } from "./users";
import { Service } from "./services";
import { Project } from "./project";

export class OffersPrices extends Auditable {
    offersPricesId: number;
    offerNo: string | null;
    offerDate: string | null;
    offerHijriDate: string | null;
    userId: number | null;
    customerId: number | null;
    customerName: string | null;
    department: string | null;
    offerValue: number;
    offerValueTxt: string | null;
    offerStatus: number | null;
    customerStatus: number | null;
    serviceId: number | null;
    branchId: number | null;
    rememberDate: string | null;
    iSsent: number | null;
    offerAlarmCheck: boolean | null;
    servQty: number | null;
    offerNoType: number | null;
    projectId: number | null;
    isContainLogo: boolean | null;
    isContainSign: boolean | null;
    printBankAccount: boolean | null;
    customerEmail: string | null;
    customerphone: string | null;
    cUstomerName_EN: string | null;
    isEnglish: number | null;
    nickName: string | null;
    description: string | null;
    introduction: string | null;
    setIntroduction: number | null;
    customerPayments: CustomerPayments[] | null;
    offersConditions: OffersConditions[] | null;
    offerService: OfferService[] | null;
    customer: Customer | null;
    users: Users | null;
    service: Service | null;
    project: Project | null;
}
