import { Auditable } from "./auditable";
import { City } from "./city";
import { Users } from "./users";
import { Employees } from "./employees";
import { Banks } from "./banks";

export class Organizations extends Auditable {
    organizationId: number;
    nameAr: string | null;
    nameEn: string | null;
    mobile: string | null;
    email: string | null;
    logoUrl: string | null;
    serverName: string | null;
    address: string | null;
    webSite: string | null;
    fax: string | null;
    cityId: number | null;
    reportType: number | null;
    taxCode: string | null;
    notificationsMail: string | null;
    branchId: number;
    vAT: number;
    vATSetting: number;
    postalCode: string | null;
    password: string | null;
    senderName: string | null;
    host: string | null;
    port: string | null;
    sSL: boolean;
    accountBank: string | null;
    isFooter: string | null;
    representorEmpId: number | null;
    postalCodeFinal: string | null;
    externalPhone: string | null;
    country: string | null;
    neighborhood: string | null;
    streetName: string | null;
    buildingNumber: string | null;
    accountBank2: string | null;
    engineering_License: string | null;
    engineering_LicenseDate: string | null;
    comDomainLink: string | null;
    comDomainAddress: string | null;
    bankId: number | null;
    bankId2: number | null;
    cSR: string | null;
    privateKey: string | null;
    publicKey: string | null;
    secreteKey: string | null;
    apiBaseUri: string | null;
    lastvesionAndroid: string | null;
    lastversionIOS: string | null;
    messageUpdateAr: string | null;
    messageUpdateEn: string | null;
    city: City | null;
    updateUserT: Users | null;
    repEmployee: Employees | null;
    bank: Banks | null;
    bank2: Banks | null;
    supportMessageAr: string | null;
    supportMessageEn: string | null;
}
