import { Auditable } from "./auditable";
import { Project } from "./project";
import { ProjectSubTypes } from "./projectSubTypes";
import { NodeLocations } from "./nodeLocations";
import { Settings } from "./settings";
import { TaskType } from "./taskType";
import { Users } from "./users";
import { ProjectRequirementsGoals } from "./projectRequirementsGoals";

export class ProjectPhasesTasks extends Auditable {
    phaseTaskId: number;
    descriptionAr: string | null;
    descriptionEn: string | null;
    parentId: number | null;
    projSubTypeId: number | null;
    type: number | null;
    userId: number | null;
    projectId: number | null;
    timeMinutes: number | null;
    timeType: number | null;
    remaining: number | null;
    isUrgent: boolean | null;
    isTemp: boolean | null;
    taskType: number | null;
    status: number | null;
    oldStatus: number | null;
    active: boolean | null;
    stopCount: number | null;
    orderNo: number | null;
    startDate: string | null;
    endDate: string | null;
    percentComplete: number | null;
    cost: number | null;
    toUserId: number | null;
    notes: string | null;
    branchId: number | null;
    locationId: number | null;
    project: Project | null;
    settingId: number | null;
    parentSettingId: number | null;
    phasePriority: number | null;
    execPercentage: number | null;
    projectSubTypes: ProjectSubTypes | null;
    mainPhase: ProjectPhasesTasks | null;
    subPhase: ProjectPhasesTasks | null;
    users: Users | null;
    nodeLocations: NodeLocations | null;
    settings: Settings | null;
    taskTypeModel: TaskType | null;
    isRead: boolean| null;
    plusTime: boolean| null;
    isConverted: number| null;
    isMerig: number | null;
    endTime: string | null;
    taskFullTime: string | null;
    excpectedStartDate: string | null;
    excpectedEndDate: string | null;
    taskLongDesc: string | null;
    isRetrieved: number | null;
    projectGoals: number | null;
    addTaskUserId: number | null;
    askDetails: number | null;
    isNew: number | null;
    taskTimeFrom: string | null;
    taskTimeTo: string | null;
    endDateCalc: string | null;
    addTaskUser: Users | null;
    projectRequirementsGoals: ProjectRequirementsGoals | null;
}
