import { Auditable } from "./auditable";
import { Pro_Municipal } from "./pro_Municipal";
import { Pro_SubMunicipality } from "./pro_SubMunicipality";
import { BuildTypes } from "./buildTypes";
import { Users } from "./users";
import { Project } from "./project";
import { Pro_Super_Phases } from "./pro_Super_Phases";
import { Pro_SupervisionDetails } from "./pro_SupervisionDetails";

export class Supervisions extends Auditable {
    supervisionId: number;
    number: number | null;
    phase: string | null;
    projectId: number | null;
    location: string | null;
    date: string | null;
    receiveNotes: string | null;
    managerNotes: string | null;
    receivedEmpId: number | null;
    receiveStatus: boolean;
    isRead: boolean;
    receiveDate: string | null;
    userId: number | null;
    branchId: number | null;
    phaseId: number | null;
    pieceNo: string | null;
    licenseNo: string | null;
    outlineNo: string | null;
    workerId: number | null;
    visitDate: string | null;
    superStatus: number | null;
    superDateConfirm: string | null;
    municipalSelectId: number | null;
    subMunicipalitySelectId: number | null;
    proBuildingTypeSelectId: number | null;
    districtName: string | null;
    proBuildingDisc: string | null;
    adwARid: number | null;
    imageUrl: string | null;
    imageUrl2: string | null;
    outlineChangetxt1: string | null;
    outlineChangetxt2: string | null;
    outlineChangetxt3: string | null;
    pointsNotWrittentxt1: string | null;
    pointsNotWrittentxt2: string | null;
    pointsNotWrittentxt3: string | null;
    municipal: Pro_Municipal | null;
    subMunicipality: Pro_SubMunicipality | null;
    buildTypes: BuildTypes | null;
    users: Users | null;
    project: Project | null;
    pro_Super_Phases: Pro_Super_Phases | null;
    supervisionDetails: Pro_SupervisionDetails[] | null;
}
