import { Auditable } from "./auditable";
import { Department } from "./department";
import { Groups } from "./groups";
import { Job } from "./job";
import { Branch } from "./branch";
import { UserPrivileges } from "./userPrivileges";
import { ProjectPhasesTasks } from "./projectPhasesTasks";
import { Project } from "./project";
import { WorkOrders } from "./workOrders";

export class Users extends Auditable {
    userId: number;
    fullName: string | null;
    jobId: number | null;
    departmentId: number | null;
    email: string | null;
    mobile: string | null;
    groupId: number | null;
    branchId: number | null;
    imgUrl: string | null;
    empId: number | null;
    userName: string | null;
    password: string | null;
    status: number | null;
    notes: string | null;
    isOnline: boolean | null;
    isAdmin: boolean | null;
    expireDate: string | null;
    lastSeenDate: string | null;
    lastLoginDate: string | null;
    lastLogOutDate: string | null;
    activationCode: string | null;
    visualCode: string | null;
    session: number | null;
    recoverPasswordLink: string | null;
    recoverPasswordDate: string | null;
    iSOnlineNew: boolean | null;
    activeTime: string | null;
    supEngineerName: string | null;
    supEngineerNationalId: string | null;
    supEngineerCert: string | null;
    stampUrl: string | null;
    timeId: number | null;
    accStatusConfirm: string | null;
    fullNameAr: string | null;
    appearWelcome: number | null;
    qrCodeUrl: string | null;
    appearInInvoicePrint: number | null;
    branchesList: number[] | null;
    department: Department | null;
    groups: Groups | null;
    jobs: Job | null;
    branches: Branch | null;
    userPrivileges: UserPrivileges[] | null;
    projectPhasesTasks: ProjectPhasesTasks[] | null;
    project: Project[] | null;
    workOrders: WorkOrders[] | null;
    isActivated: boolean | null;
    encryptedCode: string | null;
    deviceType: number | null;
    deviceTokenId: string | null;
    deviceId: string | null;
}
